# Generated by Django 4.0.3 on 2022-03-03 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=128, unique=True)),
                ('Description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionID', models.IntegerField(unique=True)),
                ('Image', models.ImageField(upload_to='')),
                ('Text', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoice',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Quizker.question')),
            ],
            bases=('Quizker.question',),
        ),
        migrations.CreateModel(
            name='OpenEnded',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Quizker.question')),
                ('Answer', models.CharField(max_length=128)),
            ],
            bases=('Quizker.question',),
        ),
        migrations.CreateModel(
            name='TrueOrFalse',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Quizker.question')),
                ('Answer', models.BooleanField()),
            ],
            bases=('Quizker.question',),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=128, unique=True)),
                ('Date', models.DateField()),
                ('Description', models.CharField(max_length=256)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizker.category')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='Quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizker.quiz'),
        ),
        migrations.CreateModel(
            name='choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChoiceID', models.IntegerField(unique=True)),
                ('Text', models.CharField(max_length=128)),
                ('Correct', models.BooleanField(default=False)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizker.multiplechoice')),
            ],
        ),
    ]
