# Generated by Django 4.0.3 on 2022-03-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizker', '0002_alter_category_options_alter_multiplechoice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
