# Generated by Django 4.0.3 on 2022-03-04 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizker', '0003_alter_question_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multiplechoice',
            options={'verbose_name_plural': 'Multiple Choice Questions'},
        ),
        migrations.AlterModelOptions(
            name='openended',
            options={'verbose_name_plural': 'Open ended Questions'},
        ),
        migrations.AlterModelOptions(
            name='trueorfalse',
            options={'verbose_name_plural': 'True or False Questions'},
        ),
    ]
