# Generated by Django 2.1.5 on 2022-03-10 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quizker', '0006_questiontype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questiontype',
            old_name='QuesitonType',
            new_name='QType',
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizker.Question'),
        ),
    ]
