# Generated by Django 2.1.5 on 2022-03-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizker', '0007_auto_20220310_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Text',
            new_name='text',
        ),
    ]
