# Generated by Django 2.1.5 on 2022-03-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizker', '0008_auto_20220311_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
