# Generated by Django 2.1.5 on 2022-03-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizker', '0012_auto_20220317_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='questionType',
            field=models.CharField(default='1', max_length=256),
            preserve_default=False,
        ),
    ]
