# Generated by Django 2.1.5 on 2022-03-17 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Quizker', '0013_quiz_questiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='Creator',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='correct',
            field=models.BooleanField(blank=True),
        ),
    ]
