# Generated by Django 2.1.5 on 2022-03-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizker', '0015_quizattempt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='Creator',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.IntegerField(),
        ),
    ]
