# Generated by Django 2.1.5 on 2022-03-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizker', '0019_auto_20220317_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='questionsCompleted',
            field=models.IntegerField(default=0),
        ),
    ]
