# Generated by Django 2.1.5 on 2022-03-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizker', '0020_auto_20220317_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='questionType',
            field=models.CharField(choices=[('OpenEnded', 'Open Ended'), ('TrueOrFalse', 'True or False'), ('MultipleChoice', 'Multiple Choice')], max_length=64),
        ),
    ]
