# Generated by Django 2.1.5 on 2022-03-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizker', '0021_auto_20220318_1056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionType',
        ),
        migrations.AddField(
            model_name='quiz',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
