# Generated by Django 2.1.5 on 2022-03-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizker', '0024_auto_20220324_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='userLikes',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
