# Generated by Django 2.1.5 on 2022-03-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizker', '0025_auto_20220324_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='desc',
            field=models.CharField(default='haha', max_length=128),
        ),
    ]
