# Generated by Django 2.1.5 on 2022-03-25 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quizker', '0025_auto_20220325_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizker.MultipleChoice'),
        ),
    ]
