# Generated by Django 2.1.5 on 2022-03-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizker', '0026_userprofile_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='desc',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nrOfCompletedQuizzes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nrOfCreatedQuizzes',
            field=models.IntegerField(default=0),
        ),
    ]
