# Generated by Django 2.1.5 on 2022-03-27 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizker', '0027_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nrOfQuizzesLiked',
            new_name='QuizzesLiked',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nrOfQuizzesCompleted',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nrOfQuizzesCreated',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='score',
        ),
    ]
