# Generated by Django 2.1.5 on 2022-03-28 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizker', '0029_profile_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
